INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (376,'petrol','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (397,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (412,'diesel','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (431,'diesel','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (450,'diesel','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (469,'diesel','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (475,'diesel','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (485,'diesel','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (504,'diesel','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (523,'lpg','euro 6',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (542,'petrol','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (561,'petrol','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (580,'petrol','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (26,'diesel','euro 6',2016,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (29,'petrol','conventional',1989,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (46,'diesel','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (63,'petrol','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (80,'petrol','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (97,'diesel','euro 2',2000,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (114,'diesel','euro 6',2017,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (131,'diesel','euro 2',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (148,'petrol','euro 2',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (165,'diesel','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (182,'diesel','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (199,'petrol','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (216,'petrol','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (231,'diesel','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (250,'petrol','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (260,'petrol','euro 3',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (270,'petrol','euro 1',1990,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (289,'petrol','euro 3',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (308,'petrol','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (327,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (346,'petrol','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (365,'petrol','euro 1',1995,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (367,'petrol','euro 1',1997,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (0,'diesel','conventional',1990,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (1,'diesel','conventional',1991,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (2,'diesel','euro 1',1992,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (3,'diesel','euro 1',1993,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (4,'diesel','euro 1',1994,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (5,'diesel','euro 1',1995,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (6,'diesel','euro 2',1996,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (7,'diesel','euro 2',1997,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (8,'diesel','euro 2',1998,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (9,'diesel','euro 2',1999,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (10,'diesel','euro 2',2000,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (11,'diesel','euro 3',2001,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (12,'diesel','euro 3',2002,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (13,'diesel','euro 3',2003,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (14,'diesel','euro 3',2004,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (15,'diesel','euro 4',2005,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (16,'diesel','euro 4',2006,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (17,'diesel','euro 4',2007,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (18,'diesel','euro 5',2008,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (19,'diesel','euro 5',2009,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (20,'diesel','euro 5',2010,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (21,'diesel','euro 5',2011,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (22,'diesel','euro 5',2012,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (23,'diesel','euro 5',2013,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (24,'diesel','euro 6',2014,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (25,'diesel','euro 6',2015,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (30,'diesel','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (31,'diesel','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (32,'diesel','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (33,'diesel','conventional',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (34,'diesel','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (35,'diesel','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (36,'diesel','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (37,'diesel','euro 1',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (38,'diesel','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (39,'diesel','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (40,'diesel','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (41,'diesel','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (42,'diesel','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (43,'diesel','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (44,'diesel','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (45,'diesel','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (47,'diesel','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (48,'diesel','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (49,'diesel','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (50,'diesel','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (51,'diesel','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (52,'diesel','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (53,'diesel','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (54,'diesel','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (55,'diesel','euro 6 up to 2017',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (56,'diesel','euro 6 up to 2017',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (57,'diesel','euro 6 up to 2017',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (58,'diesel','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (59,'petrol','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (60,'petrol','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (61,'petrol','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (62,'petrol','conventional',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (64,'petrol','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (65,'petrol','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (66,'petrol','euro 1',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (67,'petrol','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (68,'petrol','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (69,'petrol','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (70,'petrol','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (71,'petrol','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (72,'petrol','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (73,'petrol','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (74,'petrol','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (75,'petrol','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (76,'petrol','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (77,'petrol','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (78,'petrol','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (79,'petrol','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (81,'petrol','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (82,'petrol','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (83,'petrol','euro 6 up to 2017',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (84,'petrol','euro 6 up to 2017',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (85,'petrol','euro 6 up to 2017',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (86,'petrol','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (87,'diesel','conventional',1990,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (88,'diesel','conventional',1991,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (89,'diesel','euro 1',1992,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (90,'diesel','euro 1',1993,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (91,'diesel','euro 1',1994,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (92,'diesel','euro 1',1995,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (93,'diesel','euro 2',1996,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (94,'diesel','euro 2',1997,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (95,'diesel','euro 2',1998,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (96,'diesel','euro 2',1999,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (98,'diesel','euro 3',2001,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (99,'diesel','euro 3',2002,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (100,'diesel','euro 3',2003,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (101,'diesel','euro 3',2004,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (102,'diesel','euro 4',2005,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (103,'diesel','euro 4',2006,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (104,'diesel','euro 4',2007,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (105,'diesel','euro 5',2008,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (106,'diesel','euro 5',2009,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (107,'diesel','euro 5',2010,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (108,'diesel','euro 5',2011,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (109,'diesel','euro 5',2012,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (110,'diesel','euro 5',2013,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (111,'diesel','euro 6',2014,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (112,'diesel','euro 6',2015,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (113,'diesel','euro 6',2016,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (115,'diesel','conventional',1989,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (116,'petrol','conventional',1997,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (117,'petrol','conventional',2000,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (118,'petrol','conventional',2001,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (119,'petrol','conventional',2006,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (120,'petrol','conventional',1989,'truck');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (121,'diesel','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (122,'diesel','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (123,'diesel','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (124,'diesel','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (125,'diesel','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (126,'diesel','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (127,'diesel','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (128,'diesel','euro 2',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (129,'diesel','euro 2',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (130,'diesel','euro 2',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (132,'diesel','euro 2',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (133,'diesel','euro 2',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (134,'diesel','euro 2',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (135,'diesel','euro 2',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (136,'diesel','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (137,'diesel','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (138,'diesel','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (139,'diesel','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (140,'petrol','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (141,'petrol','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (142,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (143,'petrol','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (144,'petrol','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (145,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (27,'diesel','euro 6',2017,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (28,'diesel','conventional',1989,'bus');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (149,'petrol','euro 2',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (150,'petrol','euro 2',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (151,'petrol','euro 2',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (152,'petrol','euro 2',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (153,'petrol','euro 2',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (154,'petrol','euro 2',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (155,'petrol','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (156,'petrol','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (157,'petrol','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (158,'petrol','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (159,'diesel','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (160,'diesel','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (161,'diesel','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (162,'diesel','conventional',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (163,'diesel','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (164,'diesel','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (166,'diesel','euro 1',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (167,'diesel','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (168,'diesel','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (169,'diesel','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (170,'diesel','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (171,'diesel','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (172,'diesel','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (173,'diesel','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (174,'diesel','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (175,'diesel','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (176,'diesel','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (177,'diesel','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (178,'diesel','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (179,'diesel','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (180,'diesel','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (181,'diesel','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (183,'diesel','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (184,'diesel','euro 6 up to 2017',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (185,'diesel','euro 6 up to 2017',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (186,'diesel','euro 6 up to 2017',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (187,'diesel','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (188,'petrol','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (189,'petrol','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (190,'petrol','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (191,'petrol','conventional',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (192,'petrol','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (193,'petrol','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (194,'petrol','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (195,'petrol','euro 1',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (196,'petrol','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (197,'petrol','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (198,'petrol','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (200,'petrol','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (201,'petrol','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (202,'petrol','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (203,'petrol','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (204,'petrol','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (205,'petrol','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (206,'petrol','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (207,'petrol','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (208,'petrol','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (209,'petrol','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (210,'petrol','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (211,'petrol','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (212,'petrol','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (213,'petrol','euro 6 up to 2017',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (214,'petrol','euro 6 up to 2017',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (215,'petrol','euro 6 up to 2017',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (217,'diesel','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (218,'diesel','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (219,'diesel','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (220,'diesel','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (221,'diesel','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (222,'diesel','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (223,'diesel','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (224,'diesel','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (225,'diesel','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (226,'diesel','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (227,'diesel','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (228,'diesel','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (229,'diesel','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (230,'diesel','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (232,'diesel','euro 3',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (233,'diesel','euro 3',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (234,'diesel','euro 3',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (235,'diesel','euro 3',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (236,'diesel','euro 3',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (237,'diesel','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (238,'diesel','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (239,'diesel','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (240,'diesel','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (241,'petrol','euro 1',1990,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (242,'petrol','euro 1',1991,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (243,'petrol','euro 1',1992,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (244,'petrol','euro 1',1993,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (245,'petrol','euro 1',1994,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (246,'petrol','euro 1',1995,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (247,'petrol','euro 1',1996,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (248,'petrol','euro 1',1997,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (249,'petrol','euro 1',1998,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (251,'petrol','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (252,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (253,'petrol','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (254,'petrol','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (255,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (256,'petrol','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (257,'petrol','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (258,'petrol','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (259,'petrol','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (146,'petrol','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (147,'petrol','euro 2',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (263,'petrol','euro 3',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (264,'petrol','euro 3',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (265,'petrol','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (266,'petrol','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (267,'petrol','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (268,'petrol','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (269,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (271,'petrol','euro 1',1991,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (272,'petrol','euro 1',1992,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (273,'petrol','euro 1',1993,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (274,'petrol','euro 1',1994,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (275,'petrol','euro 1',1995,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (276,'petrol','euro 1',1996,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (277,'petrol','euro 1',1997,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (278,'petrol','euro 1',1998,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (279,'petrol','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (280,'petrol','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (281,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (282,'petrol','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (283,'petrol','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (284,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (285,'petrol','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (286,'petrol','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (287,'petrol','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (288,'petrol','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (290,'petrol','euro 3',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (291,'petrol','euro 3',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (292,'petrol','euro 3',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (293,'petrol','euro 3',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (294,'petrol','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (295,'petrol','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (296,'petrol','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (297,'petrol','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (298,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (299,'petrol','euro 1',1990,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (300,'petrol','euro 1',1991,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (301,'petrol','euro 1',1992,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (302,'petrol','euro 1',1993,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (303,'petrol','euro 1',1994,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (304,'petrol','euro 1',1995,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (305,'petrol','euro 1',1996,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (306,'petrol','euro 1',1997,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (307,'petrol','euro 1',1998,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (309,'petrol','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (310,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (311,'petrol','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (312,'petrol','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (313,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (314,'petrol','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (315,'petrol','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (316,'petrol','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (317,'petrol','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (318,'petrol','euro 3',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (319,'petrol','euro 3',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (320,'petrol','euro 3',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (321,'petrol','euro 3',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (322,'petrol','euro 3',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (323,'petrol','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (324,'petrol','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (325,'petrol','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (326,'petrol','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (328,'petrol','euro 1',1990,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (329,'petrol','euro 1',1991,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (330,'petrol','euro 1',1992,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (331,'petrol','euro 1',1993,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (332,'petrol','euro 1',1994,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (333,'petrol','euro 1',1995,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (334,'petrol','euro 1',1996,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (335,'petrol','euro 1',1997,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (336,'petrol','euro 1',1998,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (337,'petrol','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (338,'petrol','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (339,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (340,'petrol','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (341,'petrol','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (342,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (343,'petrol','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (344,'petrol','euro 3',2006,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (345,'petrol','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (347,'petrol','euro 3',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (348,'petrol','euro 3',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (349,'petrol','euro 3',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (350,'petrol','euro 3',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (351,'petrol','euro 3',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (352,'petrol','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (353,'petrol','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (354,'petrol','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (355,'petrol','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (356,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (357,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (358,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (359,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (360,'petrol','euro 1',1990,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (361,'petrol','euro 1',1991,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (362,'petrol','euro 1',1992,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (363,'petrol','euro 1',1993,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (364,'petrol','euro 1',1994,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (366,'petrol','euro 1',1996,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (261,'petrol','euro 3',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (262,'petrol','euro 3',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (370,'petrol','euro 1',2000,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (371,'petrol','euro 1',2001,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (372,'petrol','euro 1',2002,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (373,'petrol','euro 2',2003,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (374,'petrol','euro 2',2004,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (375,'petrol','euro 2',2005,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (377,'petrol','euro 3',2007,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (378,'petrol','euro 3',2008,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (379,'petrol','euro 3',2009,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (380,'petrol','euro 3',2010,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (381,'petrol','euro 3',2011,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (382,'petrol','euro 3',2012,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (383,'petrol','euro 3',2013,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (384,'petrol','euro 3',2014,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (385,'petrol','euro 3',2015,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (386,'petrol','euro 3',2016,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (387,'petrol','euro 4',2017,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (388,'petrol','euro 1',1989,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (389,'petrol','euro 1',1990,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (390,'petrol','euro 1',1991,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (391,'petrol','euro 1',1992,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (392,'petrol','euro 1',1993,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (393,'petrol','euro 1',1994,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (394,'petrol','euro 1',1995,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (395,'petrol','euro 1',1996,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (396,'petrol','euro 1',1998,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (398,'lpg','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (399,'diesel','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (400,'diesel','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (401,'diesel','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (402,'diesel','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (403,'diesel','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (404,'diesel','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (405,'diesel','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (406,'diesel','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (407,'diesel','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (408,'diesel','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (409,'diesel','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (410,'diesel','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (411,'diesel','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (413,'diesel','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (414,'diesel','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (415,'diesel','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (416,'diesel','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (417,'diesel','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (418,'diesel','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (419,'diesel','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (420,'diesel','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (421,'diesel','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (422,'diesel','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (423,'diesel','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (424,'diesel','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (425,'diesel','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (426,'diesel','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (427,'diesel','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (428,'diesel','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (429,'diesel','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (430,'diesel','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (432,'diesel','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (433,'diesel','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (434,'diesel','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (435,'diesel','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (436,'diesel','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (437,'diesel','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (438,'diesel','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (439,'diesel','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (440,'diesel','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (441,'diesel','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (442,'diesel','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (443,'diesel','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (444,'diesel','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (445,'diesel','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (446,'diesel','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (447,'diesel','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (448,'diesel','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (449,'diesel','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (451,'diesel','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (452,'diesel','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (453,'diesel','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (454,'diesel','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (455,'diesel','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (456,'diesel','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (457,'diesel','conventional',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (458,'diesel','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (459,'diesel','conventional',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (460,'diesel','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (461,'diesel','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (462,'diesel','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (463,'diesel','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (464,'diesel','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (465,'diesel','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (466,'diesel','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (467,'diesel','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (468,'diesel','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (470,'diesel','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (471,'diesel','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (472,'diesel','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (473,'diesel','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (474,'diesel','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (368,'petrol','euro 1',1998,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (369,'petrol','euro 1',1999,'motorcycle');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (478,'diesel','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (479,'diesel','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (480,'diesel','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (481,'diesel','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (482,'diesel','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (483,'diesel','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (484,'diesel','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (486,'diesel','conventional',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (487,'diesel','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (488,'diesel','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (489,'diesel','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (490,'diesel','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (491,'diesel','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (492,'diesel','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (493,'diesel','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (494,'diesel','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (495,'diesel','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (496,'diesel','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (497,'diesel','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (498,'diesel','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (499,'diesel','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (500,'diesel','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (501,'diesel','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (502,'diesel','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (503,'diesel','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (505,'diesel','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (506,'diesel','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (507,'diesel','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (508,'diesel','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (509,'diesel','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (510,'diesel','conventional',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (511,'lpg','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (512,'lpg','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (513,'lpg','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (514,'lpg','euro 6',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (515,'lpg','euro 6',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (516,'lpg','euro 6',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (517,'lpg','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (518,'lpg','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (519,'lpg','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (520,'lpg','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (521,'lpg','euro 6',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (522,'lpg','euro 6',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (524,'lpg','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (525,'lpg','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (526,'lpg','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (527,'lpg','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (528,'lpg','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (529,'lpg','euro 6',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (530,'lpg','euro 6',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (531,'lpg','euro 6',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (532,'cng','euro 6',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (533,'cng','euro 6',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (534,'cng','euro 6',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (535,'cng','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (536,'cng','euro 6',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (537,'petrol','ece 15/04',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (538,'petrol','ece 15/04',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (539,'petrol','ece 15/04',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (540,'petrol','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (541,'petrol','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (543,'petrol','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (544,'petrol','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (545,'petrol','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (546,'petrol','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (547,'petrol','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (548,'petrol','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (549,'petrol','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (550,'petrol','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (551,'petrol','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (552,'petrol','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (553,'petrol','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (554,'petrol','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (555,'petrol','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (556,'petrol','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (557,'petrol','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (558,'petrol','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (559,'petrol','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (560,'petrol','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (562,'petrol','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (563,'petrol','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (564,'petrol','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (565,'petrol','ece 15/04',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (566,'petrol','ece 15/04',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (567,'petrol','ece 15/04',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (568,'petrol','ece 15/04',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (569,'petrol','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (570,'petrol','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (571,'petrol','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (572,'petrol','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (573,'petrol','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (574,'petrol','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (575,'petrol','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (576,'petrol','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (577,'petrol','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (578,'petrol','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (579,'petrol','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (581,'petrol','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (476,'diesel','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (477,'diesel','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (602,'petrol','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (603,'petrol','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (604,'petrol','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (624,'petrol','ece 15/04',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (625,'petrol','ece 15/04',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (626,'petrol','ece 15/04',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (627,'petrol','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (628,'petrol','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (629,'petrol','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (630,'petrol','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (631,'petrol','euro 2',1997,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (632,'petrol','euro 2',1998,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (633,'petrol','euro 2',1999,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (634,'petrol','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (635,'petrol','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (636,'petrol','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (637,'petrol','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (638,'petrol','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (639,'petrol','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (640,'petrol','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (646,'petrol','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (647,'petrol','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (648,'petrol','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (649,'petrol','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (650,'petrol','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (651,'petrol','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (652,'petrol','ece 15/04',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (582,'petrol','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (583,'petrol','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (584,'petrol','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (585,'petrol','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (586,'petrol','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (587,'petrol','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (588,'petrol','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (589,'petrol','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (590,'petrol','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (591,'petrol','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (592,'petrol','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (593,'petrol','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (594,'petrol','ece 15/04',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (595,'petrol','ece 15/04',1990,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (596,'petrol','ece 15/04',1991,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (597,'petrol','ece 15/04',1992,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (598,'petrol','euro 1',1993,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (599,'petrol','euro 1',1994,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (600,'petrol','euro 1',1995,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (601,'petrol','euro 1',1996,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (605,'petrol','euro 2',2000,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (606,'petrol','euro 3',2001,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (607,'petrol','euro 3',2002,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (608,'petrol','euro 3',2003,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (609,'petrol','euro 3',2004,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (610,'petrol','euro 3',2005,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (611,'petrol','euro 4',2006,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (612,'petrol','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (613,'petrol','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (614,'petrol','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (615,'petrol','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (616,'petrol','euro 5',2011,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (617,'petrol','euro 5',2012,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (618,'petrol','euro 5',2013,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (619,'petrol','euro 5',2014,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (620,'petrol','euro 6 up to 2016',2015,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (621,'petrol','euro 6 up to 2016',2016,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (622,'petrol','euro 6 2017-2019',2017,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (623,'petrol','ece 15/04',1989,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (641,'petrol','euro 4',2007,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (642,'petrol','euro 4',2008,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (643,'petrol','euro 4',2009,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (644,'petrol','euro 4',2010,'car');
INSERT INTO vehicle(id,fuel,euro_star,regist_year,tipo) VALUES (645,'petrol','euro 5',2011,'car');
