/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.26
 * Generated at: 2019-11-27 13:51:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;
import java.io.*;
import java.util.*;

public final class registrarse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"icon\" href=\"imagenes/Hoja1.png\" type=\"imagenes/Hoja1.png\">\r\n");
      out.write("<title>EcoBiciZara</title>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("<link href=\"css/estilo.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/linericon/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/owl-carousel/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/lightbox/simpleLightbox.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"vendors/nice-select/css/nice-select.css\">\r\n");
      out.write("<!-- main css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		String nickError = "";
		String passError = "";
		String pass1Error = "";
		String emailError = "";
		String apeError = "";
		String vehicError = "";
		String nombError = "";
		String nickValor = "";
		String passValor = "";
		String pass1Valor = "";
		String emailValor = "";
		String apeValor = "";
		String vehicValor = "";
		String nombValor = "";
		Map<String, String> err = (Map<String, String>) request.getAttribute("errores");
		if (err != null) {
			String cabecera = "<span style=\"color:red\">";
			String fin = "</span>";
			if (err.containsKey("nickname"))
				nickError = cabecera + err.get("nickname") + fin;
			if (err.containsKey("nombre"))
				nombError = cabecera + err.get("nombre") + fin;
			if (err.containsKey("password"))
				passError = cabecera + err.get("password") + fin;
			if (err.containsKey("password1"))
				pass1Error = cabecera + err.get("password1") + fin;
			if (err.containsKey("apellidos"))
				apeError = cabecera + err.get("apellidos") + fin;
			if (err.containsKey("email"))
				emailError = cabecera + err.get("email") + fin;
			if (err.containsKey("vehiculo"))
				vehicError = cabecera + err.get("vehiculo") + fin;
			nickValor = request.getParameter("nickname");
			nombValor = request.getParameter("nombre");
			passValor = request.getParameter("password");
			pass1Valor = request.getParameter("password1");
			apeValor = request.getParameter("apellidos");
			emailValor = request.getParameter("email");
			vehicValor = request.getParameter("vehiculo");
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--================Header Area =================-->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "cabecera.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!--================Header Area =================-->\r\n");
      out.write("\t<div></div>\r\n");
      out.write("\t<!--================Breadcrumb Area =================-->\r\n");
      out.write("\t<section class=\"breadcrumb_area br_image\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"page-cover text-center\">\r\n");
      out.write("\t\t\t\t<h2 class=\"page-cover-tittle\">Registrase</h2>\r\n");
      out.write("\t\t\t\t<!--<ol class=\"breadcrumb\">\r\n");
      out.write("                        <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                        <li class=\"active\">Sermons</li>\r\n");
      out.write("                    </ol>-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--================Breadcrumb Area =================-->\r\n");
      out.write("\t<!--================Sermons work Area =================-->\r\n");
      out.write("\t<section class=\"sermons_work_area section_gap\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<form id=\"registro\" action=\"registrarse\" method=\"post\"\r\n");
      out.write("\t\t\t\tstyle=\"display: inline-block; text-align: center;\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<h3>Nuevo Usuario</h3>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"NickName\">NickName:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"nickname\" value=\"");
      out.print(nickValor);
      out.write("\" id=\"idNick\" />");
      out.print(nickError);
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"name\">Nombre:</label> <input type=\"text\" name=\"nombre\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(nombValor);
      out.write("\" id=\"idNombre\" />");
      out.print(nombError);
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"apellidos\">Apellidos:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"apellidos\" value=\"");
      out.print(apeValor);
      out.write("\" id=\"idValor\" />");
      out.print(apeError);
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password\">Contraseña:</label> <input type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"password\" value=\"");
      out.print(passValor);
      out.write("\" id=\"idPassword\" />");
      out.print(passError);
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"password1\">Repetir Contraseña:</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"password\" name=\"password1\" value=\"");
      out.print(pass1Valor);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"idPassword1\" />");
      out.print(pass1Error);
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<label for=\"email\">Dirección de Correo:</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"email\" value=\"");
      out.print(emailValor);
      out.write("\" id=\"idEmail\" />");
      out.print(emailError);
      out.write("\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<select class=\"lista1\" name=\"vehiculo\" value=\"");
      out.print(vehicValor);
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tid=\"idVehiculo\" />");
      out.print(vehicError);
      out.write("\r\n");
      out.write("\t\t\t\t\t<option selected value=\"0\"><label for=\"vehiculo\">Elige\r\n");
      out.write("\t\t\t\t\t\t\tun tipo de vehiculo</label></option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Moto\"><label for=\"moto\">Moto</label>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Coche\"><label for=\"coche\">Coche</label>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Furgoneta\"><label for=\"furgoneta\">Furgoneta</label>\r\n");
      out.write("\t\t\t\t\t</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t<br> <br> <br>\r\n");
      out.write("\t\t\t\t<center class=\"entrada1\">\r\n");
      out.write("\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"entrada1_1\" type=\"reset\" value=\"Resetear\" /> <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"entrada1_1\" type=\"submit\" value=\"Registrase\" />\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t<select>\r\n");
      out.write("\t\t\t\t\t<option data-display=\"Select\">Nothing</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">Some option</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">Another option</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\" disabled>A disabled option</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">Potato</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!--================Sermons work Area=================-->\r\n");
      out.write("\r\n");
      out.write("\t<!--================Event Blog Area=================-->\r\n");
      out.write("\t<section class=\"event_blog_area section_gap\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!--<div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"event_post\">\r\n");
      out.write("                            <img src=\"image/blog1.jpg\" alt=\"\">\r\n");
      out.write("                            <a href=\"#\"><h2 class=\"event_title\">Spreading Peace to world</h2></a>\r\n");
      out.write("                            <ul class=\"list_style sermons_category\">\r\n");
      out.write("                                <li><i class=\"lnr lnr-user\"></i>Saturday, 5th may, 2018</li>\r\n");
      out.write("                                <li><i class=\"lnr lnr-apartment\"></i>Rocky beach Church</li>\r\n");
      out.write("                                <li><i class=\"lnr lnr-location\"></i>Santa monica, Los Angeles, USA</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"#\" class=\"btn_hover\">View Details</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"event_post\">\r\n");
      out.write("                            <img src=\"image/blog2.jpg\" alt=\"\">\r\n");
      out.write("                            <a href=\"#\"><h2 class=\"event_title\">Spread Happyness to world</h2></a>\r\n");
      out.write("                            <ul class=\"list_style sermons_category\">\r\n");
      out.write("                                <li><i class=\"lnr lnr-user\"></i>Saturday, 5th may, 2018</li>\r\n");
      out.write("                                <li><i class=\"lnr lnr-apartment\"></i>Rocky beach Church</li>\r\n");
      out.write("                                <li><i class=\"lnr lnr-location\"></i>Santa monica, Los Angeles, USA</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"#\" class=\"btn_hover\">View Details</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"event_post\">\r\n");
      out.write("                            <img src=\"image/blog3.jpg\" alt=\"\">\r\n");
      out.write("                            <a href=\"#\"><h2 class=\"event_title\">Spreading Light to world</h2></a>\r\n");
      out.write("                            <ul class=\"list_style sermons_category\">\r\n");
      out.write("                                <li><i class=\"lnr lnr-user\"></i>Saturday, 5th may, 2018</li>\r\n");
      out.write("                                <li><i class=\"lnr lnr-apartment\"></i>Rocky beach Church</li>\r\n");
      out.write("                                <li><i class=\"lnr lnr-location\"></i>Santa monica, Los Angeles, USA</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <a href=\"#\" class=\"btn_hover\">View Details</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<!--================Blog Area=================-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!--================ start footer Area  =================-->\r\n");
      out.write("\t\t<footer class=\"footer-area section_gap\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3  col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"footer_title\">About Agency</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p>The world has become so fast paced that people donât\r\n");
      out.write("\t\t\t\t\t\t\t\twant to stand by reading a page of information, they would much\r\n");
      out.write("\t\t\t\t\t\t\t\trather look at a presentation and understand the message. It has\r\n");
      out.write("\t\t\t\t\t\t\t\tcome to a point</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"footer_title\">Navigation Links</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list_style\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Feature</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Services</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Portfolio</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"list_style\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Team</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Pricing</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Blog</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"footer_title\">Newsletter</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<p>For business professionals caught between high OEM price\r\n");
      out.write("\t\t\t\t\t\t\t\tand mediocre print and graphic output,</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"mc_embed_signup\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taction=\"https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tmethod=\"get\" class=\"subscribe_form relative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"input-group d-flex flex-row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input name=\"EMAIL\" placeholder=\"Email Address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonfocus=\"this.placeholder = ''\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonblur=\"this.placeholder = 'Email Address '\" required=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button class=\"btn sub-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"lnr lnr-location\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mt-10 info\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single-footer-widget instafeed\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6 class=\"footer_title\">InstaFeed</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"list_style instafeed d-flex flex-wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-01.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-02.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-03.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-04.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-05.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-06.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-07.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><img src=\"image/instagram/Image-08.jpg\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"border_line\"></div>\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tclass=\"row footer-bottom d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t<p class=\"col-lg-8 col-sm-8 footer-text m-0\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t\tCopyright &copy;\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\tAll rights reserved | This template is made with <i\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("\t\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<!--<div class=\"col-lg-4 col-sm-4 footer-social\">\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("                        <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("                    </div>-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!--================ End footer Area  =================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Optional JavaScript -->\r\n");
      out.write("\t\t<!-- jQuery first, then Popper.js, then Bootstrap JS -->\r\n");
      out.write("\t\t<script src=\"js/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/popper.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/owl-carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/mail-script.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/lightbox/simpleLightbox.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendors/nice-select/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/stellar.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
